name: Build and Deploy Client

on:
  push:
    branches:
      - main  # Trigger only on the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    
    - name: Setup SSH Agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Remove .next folder via SSH
      run: ssh -o StrictHostKeyChecking=no ${{ secrets.TEAJAR_USERNAME }}@${{ secrets.FTP_SERVER }} "rm -rf /path/to/.next"
      
    - name: Checkout code
      uses: actions/checkout@v3



    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18  # Ensure this matches your project requirements

    - name: Install dependencies
      run: npm install
      working-directory: ./client  # Navigate to client folder for npm install

    - name: Build the Next.js project
      run: npm run build
      working-directory: ./client  # Run build in client folder

    - name: List files before removing cache and standalone
      run: |
        echo "Listing .next folder contents before removal:"
        ls -R .next/  # List the contents of the .next folder
      working-directory: ./client

    - name: Remove cache and standalone folders
      run: |
        rm -rf .next/cache
        rm -rf .next/standalone
        echo "Listing .next folder contents after removal:"
        ls -R .next/  # List again after removal
      working-directory: ./client  # Ensure we're working in the correct directory
    

    - name: Upload to cPanel via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.TEAJAR_USERNAME }}
        password: ${{ secrets.TEAJAR_PASSWORD }}
        local-dir: ./client/  # Add trailing slash
        server-dir: ./  # Adjust to your server's web directory
