name: Build and Deploy Next.js to FTP

on:
  push:
    branches:
      - main  # Trigger this action on push to the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Specify the Node.js version you're using

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build Next.js
      - name: Build Next.js
        run: npm run build

      # Step 5: Copy .next folder excluding cache and standalone
      - name: Prepare .next folder
        run: |
          mkdir -p dist/.next
          cp -r .next/* dist/.next/
          rm -rf dist/.next/cache
          rm -rf dist/.next/standalone

      # Step 6: Upload to FTP server
      - name: Upload to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v5
        with:
          server: ${{ secrets.FTP_SERVER }}  # FTP server address
          username: ${{ secrets.FTP_USERNAME }}  # FTP username
          password: ${{ secrets.FTP_PASSWORD }}  # FTP password
          local-dir: dist/.next  # Local directory to deploy
          remote-dir: /path/to/ftpfolder  # Remote FTP folder path
