name: Build and Deploy Client

on:
  push:
    branches:
      - main  # Trigger only on the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install
      working-directory: ./client

    - name: Build the Next.js project
      run: npm run build
      working-directory: ./client

    - name: Delete `.next` folder on FTP server
      run: |
        echo "open ${{ secrets.FTP_SERVER }}
        user ${{ secrets.TEAJAR_USERNAME }} ${{ secrets.TEAJAR_PASSWORD }}
        cd ./  # Adjust this path to where your .next folder is located
        rmdir .next -rf
        bye" > ftp_commands.txt
        ftp -n < ftp_commands.txt

    - name: Upload new build to FTP server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.TEAJAR_USERNAME }}
        password: ${{ secrets.TEAJAR_PASSWORD }}
        local-dir: ./client/  # Path of the built Next.js project
        server-dir: ./  # Path to your server's web directory
